### PR TITLE
Add support for a Netscape cookies file

### LINKED ISSUE #3: Download doesn't start
```
py openrec-dl.py https://www.openrec.tv/live/u7ERt3xbl4i
Traceback (most recent call last):
  File "E:\openrec-dl.py", line 437, in <module>
    main()
  File "E:\openrec-dl.py", line 425, in main
    dl_movie(api_session, openrec_m.group("id"))
  File "E:\openrec-dl.py", line 216, in dl_movie
    formats_list = get_m3u8_info(m_json["media"]["url"])
  File "E:\openrec-dl.py", line 312, in get_m3u8_info
    m3u8_text = requests.get(playlist_link).text
  File "C:\Python39\lib\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "C:\Python39\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File "C:\Python39\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "C:\Python39\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'playlist.m3u8': No schema supplied. Perhaps you meant http://playlist.m3u8?
```

### PR DESCRIPTION
**Pull request by CetaceanNation**
- Add cookie jar support
- Better m3u8 handling
- Channel paging fix

To an extent, resolves #3.

### CODE REVIEW

**Comment by CetaceanNation** [comment]
@myangelaku I cannot see a publicly exposed playlist for [u7ERt3xbl4i](https://www.openrec.tv/live/u7ERt3xbl4i), so to at least solve the issue of not being able to download at all, I have modified the script to accept a Netscape cookies file (the same as you would expect youtube-dl to accept).

This requires that you have an account, but if the account has access to the stream (either via premium membership or if you have used your ability to watch two free archived videos per day), the playlist should be resolvable via a different endpoint and the download can occur.

If you get the chance please test and give feedback on whether this worked for you.

**Comment by praeludiumOrbis** [comment]
Well, I noticed that I have to manually watch the video and "confirm" that I wanna use one of the two "watching sessions" that I can use for this day.
In any case, seems like it worked for me, however, this brought up another issue which I'll also report. 
For now, it seems like this specific issue is fixed though, thanks a lot!


```
E:\>openrec-dl.py --cookies openrec.txt --write-info-json --write-thumbnail --write-live-chat https://www.openrec.tv/live/u7ERt3xbl4i
[info:u7ERt3xbl4i] no public playlist found
[info:u7ERt3xbl4i] writing video information to 'osu owo_ [u7ERt3xbl4i].info.json'
[thumbnail:u7ERt3xbl4i] writing thumbnail to 'osu owo_ [u7ERt3xbl4i].png'
[live-chat:u7ERt3xbl4i] writing live chat to osu owo_ [u7ERt3xbl4i].live_chat.json
[movie:u7ERt3xbl4i] writing video to 'osu owo_ [u7ERt3xbl4i].ts'
←[K[movie:u7ERt3xbl4i] |████████████████████████████████| 100.0% ETA 0:0076
←[?25hTraceback (most recent call last):
  File "E:\openrec-dl.py", line 515, in <module>
    main()
  File "E:\openrec-dl.py", line 503, in main
    dl_movie(pub_api_session, priv_api_session, openrec_m.group("id"))
  File "E:\openrec-dl.py", line 293, in dl_movie
    dl_m3u8_video(movie_id, movie_string, downloading_format)
  File "E:\openrec-dl.py", line 327, in dl_m3u8_video
    os.rename(f"{movie_path}.ts.tmp", f"{movie_path}.ts")
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'E:\\osu owo_ [u7ERt3xbl4i].ts.tmp' -> 'E:\\osu owo_ [u7ERt3xbl4i].ts'
```

**Comment by CetaceanNation** [comment]
Being able to automatically use the free watch sessions is a good idea, let me see if I can include that in this PR.

**Comment by CetaceanNation** [comment]
Added ability for downloader to use available free watches for downloads. Happens by default currently, thinking about adding an argument to disable. This was tested somewhat minimally but should at least work for the case presented in #3.

Will be cleaning up the playlist derivation as part of the changes and refactoring done to fix #6.

**Comment by CetaceanNation** [comment]
TIL that close != merge.

**Pull request merged**
